### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by collimarco** [sidekiq-cron/sidekiq-cron#251]
I have a simple setup of this gem in a demo application:

```
# Gemfile

gem 'sidekiq'
gem 'sidekiq-cron'
```

```
# config/initializers/sidekiq.rb

Sidekiq::Cron::Job.load_from_hash YAML.load_file('config/schedule.yml') if Sidekiq.server?
```

```
# config/schedule.yml

CronWorker:
  cron: "* * * * *"
```

```
# app/jobs/cron_worker.rb

class CronWorker
  include Sidekiq::Worker

  def perform(*args)
    # Do something
    Rails.logger.info "Cron works! #{args.inspect}"
  end
end
```

The text "Cron works!" never appears in the logs, so the job is never processed...

Note that Sidekiq itself is processing the jobs properly and logs appear for the normal jobs (only cron jobs  don't work).

I don't see anything related in the logs, so I really don't know how to debug this. However you should be able to reproduce the issue using the code above.

**Comment by collimarco** [comment]
After a lot of investigation, I have found that the job is processed properly if I use the following initializer (instead of the initializer reported in the original post):

```
# config/initializers/sidekiq.rb

Sidekiq::Cron::Job.create(name: 'CronWorker every min', cron: '* * * * *', class: 'CronWorker') if Sidekiq.server?
```

Basically `Sidekiq::Cron::Job.load_from_hash` fails silently without any errors or logs and it does not schedule the job.

Also note that adding `Sidekiq::Cron::Job.create` at the bottom of `app/jobs/cron_worker.rb` does not work: indeed that file is lazy loaded and if the job is not called from the outside, the file is never processed (you can even enter syntax errors and you won't get any logs / errors).

**Comment by collimarco** [comment]
It seems that `Sidekiq::Cron::Job.load_from_hash` works if  I use the following:

```
# config/schedule.yml

my_first_job:
  cron: "* * * * *"
  class: "CronWorker"
```

I guess that this gem does not infer the `class` from the job name, and thus it was just ignoring the job because there was no `class` key...  In any case this is not correct and very dangerous (cron jobs are silently discarded): **the gem should at least throw an error of the YAML config is not valid**. 

Related: https://github.com/ondrejbartas/sidekiq-cron/issues/243 (in my case the YAML is syntactically valid)

**Comment by collimarco** [comment]
Keep open

**Comment by collimarco** [comment]
Keep open

**Comment by collimarco** [comment]
This stale bot is really annoying.... wouldn't it be better to actually fix issues or close them manually in a very small repo like this? Or maybe just increase the "stale" timeout to something more than 2 months?

**Comment by markets** [comment]
Hey @collimarco 👋🏼, not really sure what's needed to be fixed here... Could you please try with latest version or prepare a reproducible script (a failing test or a demo app)?

**Comment by collimarco** [comment]
@markets Thanks for the reply. The reproducible steps are described in the original post.

**Comment by markets** [comment]
So your proposal, as per your last comment (https://github.com/ondrejbartas/sidekiq-cron/issues/251#issuecomment-502394626) is to raise for invalid arguments right?

We have this section describing the job arguments: https://github.com/ondrejbartas/sidekiq-cron#getting-started, under **Job properties**. But yeah, I agree, we should raise or warn for invalid arguments.
