### ISSUE TITLE
Error when running with Sidekiq v7.0.0.beta1

### ISSUE THREAD

**Issue by kaiomagalhaes** [sidekiq-cron/sidekiq-cron#370]
I know it is very early to update to the v7, but I believe that now is the moment for us to start working on it:

Error:

```
/usr/local/bundle/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:16:in `<class:Job>': undefined method `version' for nil:NilClass (NoMethodError)

      REDIS_EXISTS_METHOD = Gem.loaded_specs['redis'].version < Gem::Version.new('4.2') ? :exists : :exists?
                                                     ^^^^^^^^
	from /usr/local/bundle/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:8:in `<module:Cron>'
```

**Comment by kaiomagalhaes** [comment]
It seems that there is already an issue on Sidekiq about this issue: https://github.com/mperham/sidekiq/issues/5545

**Comment by joshRpowell** [comment]
> It seems that there is already an issue on Sidekiq about this issue: [mperham/sidekiq#5545](https://github.com/mperham/sidekiq/issues/5545)

looks like Sidekiq maintainer is offering up help to plug-in maintainers https://github.com/mperham/sidekiq/issues/5545#issuecomment-1261217429

**Comment by markets** [comment]
hey @kaiomagalhaes @joshuacronemeyer Sidekiq 7.0 support WIP in 👉🏼 https://github.com/sidekiq-cron/sidekiq-cron/pull/369.

**Comment by benkruger** [comment]
I was able to work around this by adding redis to my Gemfile
```
# Redis
# https://github.com/redis/redis-rb
gem 'redis'
```
