### ISSUE TITLE
Run schedule.yml through ERB before parsing the YAML

### ISSUE THREAD

**Issue by matthewmcgarvey** [sidekiq-cron/sidekiq-cron#372]
We upgraded our app from version 1.1 to 1.8 and it completely broke sidekiq for us with an obscure YAML parse error. It took a while to find that the error was coming from the new autoloading of `schedule.yml` that was added in 1.6

https://github.com/ondrejbartas/sidekiq-cron/blob/b7bde1ab078eaf6d851124d82f45ef0d66952de5/lib/sidekiq/cron/schedule_loader.rb#L7

The error was because we had ERB in our file which made it invalid YAML. The solution for us was to rename the file to avoid that functionality. It would be nice to update the code to send it through ERB first to work like sidekiq does.

https://github.com/mperham/sidekiq/blob/ad9442f116086424948d60ec059755f9168a6bc8/lib/sidekiq/cli.rb#L410

**Comment by markets** [comment]
@matthewmcgarvey agree! We can make a 1st pass through ERB and them load the YAML.

**Comment by markets** [comment]
@matthewmcgarvey just opened a pull request to add ERB support in the auto schedule loader: https://github.com/ondrejbartas/sidekiq-cron/pull/373. Does this work for you?
