### ISSUE TITLE
add multi DB support

### ISSUE THREAD

**Issue by thilonel** [sidekiq-cron/sidekiq-cron#384]
As Rails 7 officially supports automatic shard switching and Sidekiq also supports it (for example for multi tenancy) with CustomAttributes https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/middleware/current_attributes.rb and since I also need this in my project, I thought sidekiq-cron should also support it.

Are you open to this extension, or am I going to have to find a workaround?

**Comment by markets** [comment]
I'm open to discuss, but since I don't use this setup in any of my projects, I have no idea about the implications in the source code. Can you please elaborate in more detail or create a DRAFT pull request?

**Comment by thilonel** [comment]
Thank you for your prompt reply @markets , I will do so as soon as time allows! :)

**Comment by thilonel** [comment]
I have found a quite simple workaround. 🙈

```
schedule.yml

test_worker:
  cron: "* * * * *"
  class: "MultiTenantSchedulerWorker"
  args: ["TestWorker"]
```

And inside the `MultiTenantSchedulerWorker` we can just do: `TENANTS.each { worker_name.constantize.perform_async }`

In short: use a worker to schedule a dedicated worker for each class. I'm using a sidekiq middleware + `ActiveSupport::CurrentAttributes` internally, as that's being serialized and deserialized behind the scenes by Sidekiq.

@markets should we close? Maybe turn my workaround into some kind of documentation to save some brain cycles for others? :)

**Comment by markets** [comment]
> Maybe turn my workaround into some kind of documentation to save some brain cycles for others? :)

Yes, let's do it 👌🏼

**Comment by markets** [comment]
hey @thilonel 👋🏼 Did you had a chance to prepare a documentation update?
