### ISSUE TITLE
Keyword args aren't passed properly

### ISSUE THREAD

**Issue by LaurelOlson** [sidekiq-cron/sidekiq-cron#391]
There was an [issue](https://github.com/sidekiq-cron/sidekiq-cron/issues/274) and [PR](https://github.com/sidekiq-cron/sidekiq-cron/pull/275) to add support for using keyword args for ActiveJob. I've tried passing the `symbolize_args` param which does symbolize the args but still doesn't pass them properly for use with keyword args.

The problem seems to be that the args are all forced into an array which is then spread in as job args:

```
def enqueue_active_job(klass_const)
  klass_const.set(queue: @queue).perform_later(*enqueue_args)
end
```

so if the following is set:

```
foo_bar:
  cron: "*/1 * * * *"
  class: "FooBar"
  queue: default
  args:
    foo: "bar"
```

`args` becomes `[{foo: "bar"}]` and eventually the job is called: `FooBar.set(queue: "default").perform_later({foo: "bar"})`. This results in the same error in the original issue:

> ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: foo)

It's expecting keyword args, e.g. `FooBar.set(queue: "default").perform_later(foo: "bar")`.

For now I've forked the gem and added a separate `keyword_args` param that is then spread into as additional params, e.g. `klass_const.set(queue: @queue).perform_later(*enqueue_args, **keyword_args)` but not sure if this is necessary or if I'm just missing something / need to pass args in another way..

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah we updated also some days ago and now we get for normal scheduled jobs (via schedule.yaml) following error: 

```
wrong number of arguments (given 1, expected 0)
```

even though there are no params mentioned anywhere?

**Comment by markets** [comment]
Hi @LaurelOlson and sorry for the late reply 🙏🏼 was working on other stuff in the gem ⚙️   

To be honest I'm not sure if that's supposed to work... I'm not using `keyword_args` in my jobs, but happy to discuss/review any patch that makes it compatible with `keyword_args`. And works for all supported Ruby & Sidekiq combinations we support in our CI:

https://github.com/sidekiq-cron/sidekiq-cron/blob/48c2563a77fb9dac4ef4e881bf934ae67f1f42ab/.github/workflows/ci.yml#L11-L12
