### ISSUE TITLE
v1.10 regression all jobs are unloaded again

### ISSUE THREAD

**Issue by javinto** [sidekiq-cron/sidekiq-cron#408]
With the new release of version 1.10 any scheduled jobs (via schedule.yml) are loaded and directly unloaded again. This is a regression since version 1.9.1. Rolling back to this version solved my problem. 

Rails 6.1.7.3
Ruby 3.1.2
Sidekiq 7.0.7
redis-client 0.14.1
redis 5.0.6 (since we need this for non-sidekiq related functions)

**Comment by markets** [comment]
hey @javinto I think this is the correct behaviour using the autoloader, see https://github.com/sidekiq-cron/sidekiq-cron/pull/396 for more context.

**Comment by javinto** [comment]
Thanks for responding.

I would expect Loading after Unloading. But instead my application did Unloading after Loading!!! 

I dived further into it and the reason was that I loaded the schedule.yml file after the 
```
Sidekiq.configure_server do |config|
end
```
setup. This was old code.

I just applied the new setup:
```
Sidekiq.configure_server do |config|
  config.on(:startup) do
```

And now it all looks good!
