### ISSUE TITLE
Deprecation warning for hmset command.

### ISSUE THREAD

**Issue by phlegx** [sidekiq-cron/sidekiq-cron#411]
Hi!

I get this deprecation warning:

`[sidekiq#5788] Redis has deprecated the 'hmset' command, called at [".../sidekiq-cron-1.10.0/lib/sidekiq/cron/job.rb:472:in 'block in save'"]`

**Versions**

- Ruby 3.2.2
- Redis 6.2.5
- Rails 7.0.4.3
- Sidekiq cron 1.10.0

**Comment by phlegx** [comment]
I see the problem solved in #410 merged in master! Can this be released please?

**Comment by markets** [comment]
@phlegx I'll prepare a new release next week

**Comment by gbs4ever** [comment]
I am also getting the same   error ```Redis has deprecated the `hmset`command, called at ["/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-cron-1.10.0/lib/sidekiq/cron/[job.rb](https://my.papertrailapp.com/groups/22269542/events?q=%22job.rb%22&focus=1592367969894293512&selected=1592367969894293512):472:in `block in save'"]```

**Comment by markets** [comment]
Released 🚀 

- https://github.com/sidekiq-cron/sidekiq-cron/releases/tag/v1.10.1
- https://rubygems.org/gems/sidekiq-cron/versions/1.10.1
