### ISSUE TITLE
Parsing in UTC?

### ISSUE THREAD

**Issue by milgner** [sidekiq-cron/sidekiq-cron#415]
The Readme mentions that when Rails is present, it will use the time zone of Rails. I can't seem to find a mechanism to configure this, though.

Is there a way to interpret cron expressions in UTC? I.e. 

```
cron: "0 0 * * *"
```

Is supposed to run the job at `00:00` UTC, not in local time. Since there are servers in different timezones running the app, it would be very impractical to have different `schedule.yml` files on each of them.

**Comment by jmettraux** [comment]
You could specify the timezone directly in the `schedule.yml`:

```yaml
cron: "0 0 * * * UTC"
```

or if you need another timezone:

```yaml
cron: "0 0 * * * Asia/Shangai"
```

**Comment by milgner** [comment]
That's nice - I wasn't aware of that syntax. Thank you for the quick feedback!
