### ISSUE TITLE
Can't use ActiveJob by default

### ISSUE THREAD

**Issue by maxfurman** [sidekiq-cron/sidekiq-cron#424]
I need to enqueue all sidekiq-cron jobs through ActiveJob, i.e. set the active_job config option to true, in order for them to work with other parts of my system. Of course I can set active_job: true on every item in my schedule.yml file, but I would prefer to set a config option somewhere and then not have to remember it when adding a new cron job. AFAICT there is no way to do that in the current implementation. Am I wrong?

**Comment by markets** [comment]
Hello @maxfurman 

Currently, this global option doesn't exist, but maybe it makes sense 🤔? Happy to discuss or review any pull request in this direction.

**Comment by maxfurman** [comment]
My idea here is to add support for an additional key in `Sidekiq::Options`, maybe `Sidekiq::Options[:cron_job_defaults]`, that would be a hash matching the options that Sidekiq::Cron::Job already accepts. Then we could merge that into the input args when a new Job instance is initialized. 

It's a pretty small change overall, I can put together a PR if this direction is acceptable.

**Comment by markets** [comment]
Not sure about this solution 🤔 maybe it's a bit confusing to allow defaults for all [properties](https://github.com/sidekiq-cron/sidekiq-cron#job-properties)?

To be honest, I don't know why we need a flag (I wasn't maintaining this project at that time), it seems we already have code for "autodetection":
https://github.com/sidekiq-cron/sidekiq-cron/blob/78eb493adbfeb908861ec9b3a76e5e7a01adf339/lib/sidekiq/cron/job.rb#L81-L85

Maybe we can explore this path? I mean, automatically use Active Job if possible.

**Comment by maxfurman** [comment]
There does seem to be autodetection there. For my use case I also need to set the queue_name_prefix for all jobs. I can do this through YAML labels but that feels sloppy to me, and requires me to add an invalid "defaults" job to schedule.yml. I understand why you're hesitant to allow overrides of, say, the enabled/disabled flag. Maybe an allowlist of overridable properties would be useful.
