### ISSUE TITLE
RSpec testing for models that create cronjobs as callbacks

### ISSUE THREAD

**Issue by dsusviela** [sidekiq-cron/sidekiq-cron#425]
Hello everyone, thanks for the hard work in the contributions to sidekiq-cron

It would be a neat feature to change how we are saving things in the `Sidekiq::Cron::Job`. Maybe I am missing something but in [this snippet](https://github.com/sidekiq-cron/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L462-L480) 

```ruby
def save
  # If job is invalid, return false.
  return false unless valid?

  Sidekiq.redis do |conn|

    # Add to set of all jobs
    conn.sadd self.class.jobs_key, [redis_key]

    # Add informations for this job!
    conn.hset redis_key, to_hash.transform_values! { |v| v || "" }

    # Add information about last time! - don't enque right after scheduler poller starts!
    time = Time.now.utc
    exists = conn.public_send(REDIS_EXISTS_METHOD, job_enqueued_key)
    conn.zadd(job_enqueued_key, time.to_f.to_s, formatted_last_time(time).to_s) unless exists == true || exists == 1
  end
  Sidekiq.logger.info { "Cron Jobs - added job with name: #{@name}" }
end
```

We can see that the gem is accessing directly `redis`, which is a problem for testing environments when using `Sidekiq::Cron::Job.create`.

**Comment by markets** [comment]
Hi @dsusviela thanks for your words! really appreciated!

What do you exactly mean by "a problem"? Do you want to somehow mockup the `redis` object? This will require to implement some kind of "adapter" thing, as this code `Sidekiq.redis` is used in several places. Do you know if Sidekiq itself does something similar?

**Comment by dsusviela** [comment]
Hey @markets!

Maybe I can give a more practical example:

Suppose I have a Rails App, that has a model named `Task`. I will write some code from memory so excuse me if its not really runnable. If you want I can give an actual runnable script.

```ruby
class Task < ActiveRecord
  after_save :create_task

  def create_task
    Sidekiq::Cron::Job.create("some args here")
  end
end
```

Suppose now that I want to run the following test suite (in my case rspec):

```ruby
describe Task do
  context "when creating a valid task" do
    it "creates a sidekiq cron job"
      # i know this matcher doesn't exist but bear with me
      expect(Task.create("take dog to the vet")).to_have_created_sidekiq_cron
    end
  end
end
```

Now if i go to `localhost:3000/sidekiq/cron` I can see the task "take dog to the vet".

In my opinion I should be able to configure the backend for sidekiq cron in an initializer file or I should be able to include a file like we do in normal sidekiq ie, `sidekiq/rspec` that solves this problem.

However maybe my whole approach is wrong, and the smell that I have comes from a different angle (like creating cron jobs from an AR callback).

**Comment by markets** [comment]
Would be nice if we can re-use any of those `sidekiq` provided helpers/classes to provide similar strategy for testing `sidekiq-cron`. Maybe we can't re-use it, but we can use it as inspiration to provide similar stuff. Happy to review any PR in this direction.

**Comment by schnika** [comment]
@dsusviela directly creating callbacks from an AR callback is not the cleanest way to do it. However since sidekiq-cron is well tested, I would stub this dependency and just accept the fact, that when `Sidekiq::Cron::Job.create` is being called, that everything that comes after that works as expected.

If you want to have a working integration spec you can think about setting `https://github.com/sds/mock_redis` as your redis backend for sidekiq. That should work as well, right?
