### ISSUE TITLE
Not respecting SSL_PARAMS  for redis on heroku

### ISSUE THREAD

**Issue by michael-ciocca** [sidekiq-cron/sidekiq-cron#434]
I am trying to upgrade from the basic redis plan to premium-0 on heroku. This requires setting  ` ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } })`  as options to redis. It appears that sidekiq-cron is not respecting this configuration, as the app crashes with a redis self-signed certificate error with sidekiq-cron installed. Uninstalling sidekiq-cron and restarting the dyno fixes the issue.

Am I just missing something here for sidekiq cron or is it not respecting our redis configuration?

**Comment by markets** [comment]
Hello @michael-ciocca 👋🏼 

Sidekiq-Cron doesn't modify the Redis configuration, in fact, we always access internally (to read-write jobs) to the Redis instance using the Sidekiq interface: `Sidekiq.redis { ... }`, so in theory we rely on how you configured your Sidekiq.

**Comment by michael-ciocca** [comment]
Thanks @markets. This is what I figured but wanted to be sure. Not sure why removing sidekiq cron fixes the issue, but I'l close this and look into it more on my end.

**Comment by markets** [comment]
No prob! If you finally find any extra information, please let us know.
