### ISSUE TITLE
Add a strict evaluation mode for cron expressions

### ISSUE THREAD

**Issue by kevinrobell-st** [sidekiq-cron/sidekiq-cron#450]
Right now Sidekiq Cron uses the Fugit gem internally to parse cron expressions but the method used is permissive by default. It would be nice to have a way to turn on stricter cron expression checks.

Basically, what I'm proposing is something like this where the strict option is enabled somehow when configuring Sidekiq Cron.

```diff
diff --git a/lib/sidekiq/cron/job.rb b/lib/sidekiq/cron/job.rb
index e571f18..61b8766 100644
--- a/lib/sidekiq/cron/job.rb
+++ b/lib/sidekiq/cron/job.rb
@@ -452,7 +452,11 @@ module Sidekiq
           errors << "'cron' must be set"
         else
           begin
-            @parsed_cron = Fugit.do_parse_cronish(@cron)
+            @parsed_cron = if strict?
+              Fugit.do_parse(@cron, :multi => :fail)
+            else
+              Fugit.do_parse_cronish(@cron)
+            end
           rescue => e
             errors << "'cron' -> #{@cron.inspect} -> #{e.class}: #{e.message}"
           end
@@ -593,7 +597,11 @@ module Sidekiq
       private
 
       def parsed_cron
-        @parsed_cron ||= Fugit.parse_cronish(@cron)
+        @parsed_cron ||= if strict?
+          Fugit.do_parse(@cron, :multi => :fail)
+        else
+          Fugit.do_parse_cronish(@cron)
+        end
       end
 
       def not_enqueued_after?(time)

```

The main error I'm trying to prevent here is the multi expression error since that is ignored by the `Fugit.do_parse_cronish` method. It also ignores any extra words after the first parsed cron expression.

```rb
irb(main):003:0> Fugit.do_parse_cronish("every day at 3:15 and 4:30")
=> #<Fugit::Cron:0x0000000120d126a0 @original="15 3 * * *", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[15], @hours=[3], @monthdays=nil, @months=nil, @weekdays=nil, @zone=nil, @timezone=nil>
irb(main):004:0> Fugit.do_parse_cronish("every day at 3:15 and 4:30", :multi => :fail)
=> #<Fugit::Cron:0x0000000120abd080 @original="15 3 * * *", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[15], @hours=[3], @monthdays=nil, @months=nil, @weekdays=nil, @zone=nil, @timezone=nil>
irb(main):005:0> Fugit.do_parse("every day at 3:15 and 4:30")
=> #<Fugit::Cron:0x000000011100e170 @original="15 3 * * *", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[15], @hours=[3], @monthdays=nil, @months=nil, @weekdays=nil, @zone=nil, @timezone=nil>
irb(main):006:0> Fugit.do_parse("every day at 3:15 and 4:30", :multi => :fail)
Traceback (most recent call last):
       16: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
       15: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
       14: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       13: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
       12: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
       11: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
       10: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
        9: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/bin/irb:23:in `<top (required)>'
        8: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/bin/irb:23:in `load'
        7: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        6: from (irb):6
        5: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/fugit-1.9.0/lib/fugit/parse.rb:32:in `do_parse'
        4: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/fugit-1.9.0/lib/fugit/parse.rb:25:in `parse'
        3: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/fugit-1.9.0/lib/fugit/parse.rb:9:in `parse_nat'
        2: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/fugit-1.9.0/lib/fugit/nat.rb:24:in `parse'
        1: from /Users/kevinrobell/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/fugit-1.9.0/lib/fugit/nat.rb:642:in `to_crons'
ArgumentError (multiple crons in "every day at 3:15 and 4:30" - {:monthday=>(slot :monthday "*" {:weak=>true})})
```

**Comment by markets** [comment]
Hello 👋🏼 @kevinrobell-st and thanks for your feedback! I think that makes sense, as it provides a better UX for developers. But I don't like to introduce a lot of configuration flags, maybe it makes sense as a default behavior?

Note that, in the first snippet, the code is around a begin/rescue block, so it won't raise anyway.

**Comment by kevinrobell-st** [comment]
It'd be great if it was the default behavior. I was just thinking about backwards compatibility when I suggested a config flag there. Either way works for me.

**Comment by markets** [comment]
Even with backwards compatibility in mind, it probably makes sense to make just the default behavior, as if I understood this correctly, the current parsing doesn't warn for invalid crons?

@jmettraux what do you think about that?

**Comment by jmettraux** [comment]
`Fugit.parse_cron` and `.do_parse_cron` are about cron expressions in the `man 5 crontab` sense, while `Fugit.parse_cronish` and `.do_parse_cronish` accept cron expressions and strings like "every day" or "every month on the 1st at 11:00".

The change by @kevinrobell-st implies that `strict?` means "should restrict to only cron expressions?". Maybe `strict_cron?` could better convey the objective.

To really go the strict way, I think the diff below would be better, with `do_parse_cron` instead of `do_parse` which accepts "at" and "in" expressions and time point expressions:

```diff
--- a/lib/sidekiq/cron/job.rb
+++ b/lib/sidekiq/cron/job.rb
@@ -452,7 +452,11 @@ module Sidekiq
           errors << "'cron' must be set"
         else
           begin
-            @parsed_cron = Fugit.do_parse_cronish(@cron)
+            @parsed_cron = if strict?
+              Fugit.do_parse_cron(@cron, :multi => :fail)
+            else
+              Fugit.do_parse_cronish(@cron)
+            end
           rescue => e
             errors << "'cron' -> #{@cron.inspect} -> #{e.class}: #{e.message}"
           end
@@ -593,7 +597,11 @@ module Sidekiq
       private
 
       def parsed_cron
-        @parsed_cron ||= Fugit.parse_cronish(@cron)
+        @parsed_cron ||= if strict?
+          Fugit.do_parse_cron(@cron, :multi => :fail)
+        else
+          Fugit.do_parse_cronish(@cron)
+        end
       end
 
       def not_enqueued_after?(time)
```

**Comment by markets** [comment]
Thank you so much for your input @jmettraux 👌 really appreciated!

@kevinrobell-st feel free to send a patch, we can use the Configuration class to add a flag: 

https://github.com/sidekiq-cron/sidekiq-cron/blob/b92fcee9dba261043d3f1689162a1dd7e209983b/lib/sidekiq/cron.rb#L18

**Comment by kevinrobell-st** [comment]
Yeah, I hadn't considered that. I guess I'd like to keep the natural syntax and have stricter evaluation at the same time but `Fugit.do_parse` allows for durations which doesn't work for Sidekiq Cron and `Fugit.do_parse_cronish` doesn't fail when there are multiple cron expressions and `Fugit.do_parse_cron` doesn't allow for the natural language syntax.

**Comment by kevinrobell-st** [comment]
The only work around I can think of is to do something like this.

```rb
@parsed_cron ||= if strict?
  cron = Fugit.parse_cron(@cron) || Fugit.parse_nat(@cron, :multi => :fail)
  raise ArgumentError, "invalid cron string #{@cron.inspect}" if cron.nil?
  cron
else
  Fugit.do_parse_cronish(@cron)
end
```

This is much less straightforward than what I was originally thinking of though. It looks like the multiple cron strings can only occur with natural language as well. Would something like this be acceptable or is it just not worth the effort for stricter evaluation?

**Comment by jmettraux** [comment]
Working with a set of specs would help (me at least). Once a level of clarity has been established, a solution can be derived and sustained. What comes in? What is OK? What fails? and when `strict_whatever?` is on, what fails?

I'd be happy to help if a change, a new method, within [fugit](https://github.com/floraison/fugit) is then deemed necessary.

Sorry, I see code, I cannot resist:
```ruby
@parsed_cron ||= if strict?
  Fugit.parse_cron(@cron) ||
  Fugit.parse_nat(@cron, :multi => :fail) ||
  fail(ArgumentError.new("invalid cron string #{@cron.inspect}")
else
  Fugit.do_parse_cronish(@cron)
end
```

**Comment by kevinrobell-st** [comment]
> Working with a set of specs would help (me at least). Once a level of clarity has been established, a solution can be derived and sustained. What comes in? What is OK? What fails? and when `strict_whatever?` is on, what fails?

Good point.

- Valid
  - `* * * * *`
  - `every Thursday`
  - `every day at 5:00 and 8:00`
- Invalid
  - `every day at 3:33 and 5:55`

Currently, the last one will be parsed as `every day at 3:33`.  

> I'd be happy to help if a change, a new method, within [fugit](https://github.com/floraison/fugit) is then deemed necessary.

❤️

> Sorry, I see code, I cannot resist:
> 
> ```ruby
> @parsed_cron ||= if strict?
>   Fugit.parse_cron(@cron) ||
>   Fugit.parse_nat(@cron, :multi => :fail) ||
>   fail(ArgumentError.new("invalid cron string #{@cron.inspect}")
> else
>   Fugit.do_parse_cronish(@cron)
> end
> ```

That is simpler. Feels more shell like. I'll be honest I don't think I've ever seen `Kernel#fail` in the wild. I learned something new.

**Comment by jmettraux** [comment]
> That is simpler. Feels more shell like. I'll be honest I don't think I've ever seen Kernel#fail in the wild. I learned something new.

`fail` for new errors, `raise` caught errors. If I remember correctly, I picked the habit from [Exceptional Ruby](https://pragprog.com/titles/ager/exceptional-ruby/).

**Comment by kevinrobell-st** [comment]
It looks like one reason I'd never heard of `fail` before is that it gets automatically corrected to `raise` by RuboCop as of 2015. I'm not sure I agree with the reasoning though.

- https://github.com/rubocop/ruby-style-guide/issues/512
