### ISSUE TITLE
Cron tab in Web UI miscolored in Sidekiq Pro v7

### ISSUE THREAD

**Issue by joevandyk** [sidekiq-cron/sidekiq-cron#451]
![image](https://github.com/sidekiq-cron/sidekiq-cron/assets/1179/3c641b1a-8338-4217-a9e9-53a782885fce)

**Comment by markets** [comment]
Hello @joevandyk,

Which versions of sidekiq and sidekiq-cron are you using?

**Comment by joevandyk** [comment]
This occurred after we upgraded sidekiq and sidekiq-cron and only lasted for a day, it looks fine now. I wonder if sidekiq or this gem has some CSS that gets cached for a certain amount of time.
