### ISSUE TITLE
Violation of Sidekiq Best Practices

### ISSUE THREAD

**Issue by pboling** [sidekiq-cron/sidekiq-cron#453]
Rule #4 is to never use the term "Worker"

> 4. Use Precise Terminology
> Within the Sidekiq ecosystem, the term worker is ambiguous and thus meaningless.
> Sidekiq::Job is a module included in a job class.
> If you have 10 "workers" executing jobs, you have 10 threads.
> If you start a "worker", you have a process.
> If you have 10 "workers" enqueued, you have 10 jobs.
> Use those terms: job class, thread, process or job. Dump "worker" from your vocabulary.

[reference](https://github.com/sidekiq/sidekiq/wiki/Best-Practices#4-use-precise-terminology)

This gems' README uses the term `worker`, and it has me confused.  It should be updated to avoid using the completely ambiguous term `worker`.

> Checks for new jobs to schedule every 30 seconds and doesn't schedule the same job multiple times when more than one Sidekiq worker is running.

We almost always have hundreds of "workers", assuming it means "threads", actively running, so does that mean I can't use this gem?  If not, what does it mean?

**Comment by markets** [comment]
Hello @pboling 👋🏼 

Ok yes, you're right! I think we should probably update those docs to clarify what it means in the Sidekiq-Cron context, but using the "official" Sidekiq terminology. Here we have a more detailed description about how this gem works under the hood: https://github.com/sidekiq-cron/sidekiq-cron?tab=readme-ov-file#under-the-hood. But in summary, in that paragraph it means "process".

**Comment by pboling** [comment]
@markets I'd love to!  Will try to get to it by the weekend.

**Comment by markets** [comment]
Hello @pboling, 

Did you had the chance to prepare a PR to enhance these docs? Would love to have this clarification in place for future readers.

**Comment by pboling** [comment]
Sorry, no. Everything I am working on is critical at the moment and I'm over subscribed.

**Comment by markets** [comment]
No prob @pboling! I'm also maintaining a lot of open source projects and I know that feeling 😅

I'll try to take a look asap, I now think that's an important detail to document well and probably some quick replace worker => process will make the job.

Thanks for pointing out this documentation issue! And of course, if you find the time and the motivation, I'd really happy to review and merge a PR in this direction.

PS I'll keep the issue open until this is fixed
