### ISSUE TITLE
[Question] Monitor Sidekiq Cron Workers

### ISSUE THREAD

**Issue by rslhdyt** [sidekiq-cron/sidekiq-cron#456]
Hi,

First, thanks for all the hard work you put into keeping this gem running smoothly. It's really helpful.

Recently, I ran into a problem because some cron workers didn't run like they were supposed to. This happened because the pod restarted, which was caused by some bad queries inside the worker class. I'm wondering how you all keep track of whether all the sidekiq-cron processes are running as they should.

I've been thinking about using sidekiq middleware to store a key before a worker starts and then remove the key once the worker is done. This way, I could check if the key is still there to know if the worker didn't run correctly. What do you think about this idea?

**Comment by markets** [comment]
Hello @rslhdyt,

I'm actually using the https://github.com/smartinez87/exception_notification gem. You can use for example the [manual notification](https://github.com/smartinez87/exception_notification?tab=readme-ov-file#manually-notify-of-exceptions) approach inside your job class. So if any error (or specific condition) raises inside your job, you'll receive a notification via email, Slack, Datadog, ...

It seems you may also want to know if the job even run (not only if there is an error). For that, your idea seems feasible, why not? The gem didn't provide any api/option to handle that, as we rely on the Sidekiq process itself to boot our scheduler.
