### ISSUE TITLE
Ability to configure the past schedule interval

### ISSUE THREAD

**Issue by fatkodima** [sidekiq-cron/sidekiq-cron#463]
We are going to use this gem in our application, instead of our custom solution. 

One problem we had and this gem does not fully solve is that if sidekiq is restarting while some schedule is about to run, we may loose that schedule. For example, if we have some job to run at `15:00` and deployment is happening at `14:57` (and sidekiq is restarted) and sidekiq is back up to live at 15:03, then we missed that job to be scheduled.

This can be solved by zero downtime deployments or smaller more frequent jobs or some refactoring, but that is not currently achievable.

If the `60` seconds from https://github.com/sidekiq-cron/sidekiq-cron/blob/abdb335a796d3cc3841b8029ee8da26f0bde08e6/lib/sidekiq/cron/job.rb#L668-L672 will be configurable, then this will save us and a bit older missed schedules will be considered.

Are you open for this feature? Would be glad to provide a PR.

**Comment by markets** [comment]
Hey @fatkodima 👋🏼 

I have very little context about when this was added, it seems it was here: https://github.com/sidekiq-cron/sidekiq-cron/pull/73.

So, a priori, I have no objections on adding a new configuration flag for that. Please, feel free to submit a patch.

**Comment by freemanoid** [comment]
That would be super helpful. Given that double enqueuing is not possible, it should not cause any degradation.
