### ISSUE TITLE
Missing some schedule instance on sidekiq-cron

### ISSUE THREAD

**Issue by Ramkumar0508** [sidekiq-cron/sidekiq-cron#464]
![image (1)](https://github.com/sidekiq-cron/sidekiq-cron/assets/80701324/9be993ae-04e3-4f86-8d12-d5a5372ff4f4)

Sidekiq Version: 5.0.0
Sidekiq-cron Version: 1.2.0

Hello, 
    We've observed that some worker schedule instances are missing. This inconsistency occurs regardless of the cron timing configuration. Initially, we set the cron expression to run the worker every hour (1 hour). However, we noticed delays where the worker would sometimes execute after 4 or 6 hours, deviating significantly from the intended schedule. Subsequently, we adjusted the cron expression to a more frequent interval of 30 minutes, but the issue persists.
    
Could you please advise on potential causes for this behaviour and suggest any solutions?

**Comment by markets** [comment]
Hey @Ramkumar0508, the versions you're using are a bit old. We only officially support Sidekiq v6 and v7 (see our CI: https://github.com/sidekiq-cron/sidekiq-cron/blob/master/.github/workflows/ci.yml#L12). I suggest to upgrade to at least the latest Sidekiq v6 and latest Sidekiq-Cron (which is v1.12.0: https://github.com/sidekiq-cron/sidekiq-cron/releases/tag/v1.12.0)

**Comment by Ramkumar0508** [comment]
@markets Thanks for your message. We will upgrade the sidekiq and verify the changes.
