### ISSUE TITLE
load_from_array! showing "Cron Jobs - added job with name ..." for previously added jobs

### ISSUE THREAD

**Issue by KieranP** [sidekiq-cron/sidekiq-cron#467]
We have over a dozen cron jobs, and each time we deploy, we are seeing a bunch of "Cron Jobs - added job with name ..." messages, even though the jobs have previously been added and no changes were made. Would be nice to only see these messages when jobs are added for the first time.

**Comment by markets** [comment]
Hey @KieranP 👋🏼 

Actually, on each restart we are cleaning all the jobs and add them again, in order to prevent "removed" jobs to keep appearing in the schedule, see more: #405, #431. So let's say this is the expected behavior.

**Comment by KieranP** [comment]
@markets Thank you for responding and sorry for my delayed response. You said: "we are cleaning all the jobs and add them again". but I'm not sure that is the case, at least, not in the master branch.

When we use load_from_array!, it appears to do two things: Removes old jobs that should no longer be present (via [destroy_removed_jobs](https://github.com/sidekiq-cron/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L544-L557) method) and then insert/replace the remaining (via [load_from_array](https://github.com/sidekiq-cron/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L272-L279) method). It does not seem to erase jobs that existed before and should still exist.

Instead, when a cron job is saved (https://github.com/sidekiq-cron/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L476-L493), it uses hset to replace the existing job information, which in my case, hasn't changed between deploys. The end of that method then always logs out "added job" even though really it replaced it with the exact same info (i.e. no change).

I suspect it would be a relatively simple thing within the save method to fetch all existing jobs (like `destroy_removed_jobs` already does), compare the old attributes with the new, and only output the log line if a job is new/changed.

**Comment by sandip-mane** [comment]
@markets we were clearing all jobs but some folks reported issues with the default behaviour so we had to undo it. Ref: https://github.com/sidekiq-cron/sidekiq-cron/pull/427/files

@KieranP could you please check what version you are using? I don't think this should be happening in the latest version.

**Comment by KieranP** [comment]
@sandip-mane Can confirm I am running on the latest version. The current code continues to output "Cron Jobs - added job with name ..." even though the job already existed.

**Comment by sandip-mane** [comment]
The jobs are not RE-ADDED to the schedule, we are just printing it every time. i.e. We can use the `exists` check for logger similar to **line 490**.

https://github.com/sidekiq-cron/sidekiq-cron/blob/d409af416afa83362767880f57bb4bf432a80708/lib/sidekiq/cron/job.rb#L489-L492


@markets let me know if I should make this change.

**Comment by markets** [comment]
Yes please @sandip-mane! Feel free to send a PR to improve this.

**Comment by sandip-mane** [comment]
Got busy with the work and missed it. Hopefully this will be done with #476.

**Comment by markets** [comment]
Closed by #476
