### ISSUE TITLE
Sidekiq 7.3 compatibility

### ISSUE THREAD

**Issue by mperham** [sidekiq-cron/sidekiq-cron#468]
Sidekiq 7.3 will remove support for inline styling and scripts. This means you'll need to move your dynamic styling into a separate CSS file and flag it with the current nonce.

```html
<link href="<%= root_path %>stylesheets/sidekiq-cron.css" media="screen" rel="stylesheet" type="text/css" nonce="<%= csp_nonce %>" />
```

Where `sidekiq-cron.css` should go into a directory which you have added to Sidekiq::Web's asset paths. I don't have an API for this yet -- TBD.

See sidekiq/sidekiq#6270

**Comment by markets** [comment]
Thanks for the info @mperham! Will take a look asap this new API is defined. 

Just a question for now, I understand this will only work with Sidekiq 7.3+ right? That means, that we'll need to somehow maintain 2 ways (pre and post 7.3) of "injecting" our assets to Sidekiq Web UI?

**Comment by mperham** [comment]
Yep, unfortunately that is correct today. I'm open to suggestions for how to make this easier. This change is designed to remove an entire style of attack on the Web UI (XSS) but requires all /sidekiq pages to be compliant or they will break. There's 4-5 popular Sidekiq extensions so I'm hoping this will be doable but some of them have significant UI.

**Comment by markets** [comment]
Hello @mperham, 

I reviewed all our front-end part for the Web UI, and we are not using any external js or css, just a couple of dynamically-generated inline styles: https://github.com/search?q=repo%3Asidekiq-cron%2Fsidekiq-cron%20style&type=code. Do you think this is gonna be a problem?

**Comment by mperham** [comment]
We're going to allow inline styles for 7.3 but they'll need to move to static classes + predefined javascript for 8.0. Right now I'm writing an example extension which you can use as a reference for how to do things the "correct" way.

**Comment by markets** [comment]
Ok, thanks Mike! Please, share the example once you have a chance, I'll try refactor our inline styles asap, so we'll prepared for compatibility with the future Sidekiq release.

**Comment by mperham** [comment]
Here's the new registration API and example extension. Let me know what you think, everything is still malleable so feedback would be appreciated. I still need to add a test.

https://github.com/sidekiq/sidekiq/pull/6292

**Comment by satyakampandya** [comment]
> Remove all the current usage of inline styles (instead of adding custom css, I'd much prefer to simplify the view layer to use existing css classes or another solution that avoids inline styles). Ref: https://github.com/search?q=repo%3Asidekiq-cron%2Fsidekiq-cron+style%3D&type=code

Hi @markets,

I've started working on cleaning up the inline CSS as discussed. However, I noticed that the "Show All" button on the CronJob listing page isn't functioning as expected. When clicked, it doesn’t display the full message. Could you please confirm if this is a known issue?

To resolve this, we might need to add a few lines of JavaScript, or alternatively, we could consider removing the button from the UI if it's not essential.

**Comment by satyakampandya** [comment]
> Use new API to inject web stuff into Sidekiq Panel (if Sidekiq >= 7.3). Refs: https://github.com/sidekiq/sidekiq/pull/6292, https://github.com/sidekiq-cron/sidekiq-cron/blob/master/lib/sidekiq/cron/web.rb

Hi @markets & @mperham

As I'm working on adapting the new API for injecting web components into the Sidekiq Panel (for Sidekiq >= 7.3), I noticed that this change would require a folder structure update to accommodate the new registration method for web extensions.
```ruby
# NEW API IN 7.3.0
# This new way allows you to serve your own static assets
# and provide localizations for any strings in your extension.

Sidekiq::Web.register(SidekiqExt::RedisInfo::Web,
  name: "redis_info",
  tab: ["Redis"],              # The name on your Tab(s)
  index: ["redis_info"],       # The path to the root page(s) of your extension within the Web UI, usually "/sidekiq/" + index
  root_dir: SidekiqExt::RedisInfo::Web::ROOT,
  asset_paths: ["css", "js"]) do |app|   # Paths within {root}/assets/{name} to serve static assets
  # you can add your own middleware or additional settings here
end
```
Before proceeding, I wanted to clarify our approach:

- Will the next release of sidekiq-cron require users to use at least Sidekiq 7.3, or are we planning to support older versions as well?
- If we're supporting older versions, how should we handle the folder structure changes to ensure compatibility across different Sidekiq versions?

Your guidance on this would be much appreciated!

**Comment by markets** [comment]
Hey @satyakampandya 👋🏼 

Our plans (Sidekiq-Cron) is to keep support for both versions, that's why I'd prefer to avoid injecting custom assets (js, css, images, fonts, ...) for now. 

As I commented in another issue, my original idea to make it as simple as possible:
- Use new API to inject web stuff into Sidekiq Panel (if Sidekiq >= 7.3, keep current hook for current versions). Refs: https://github.com/sidekiq/sidekiq/pull/6292 & https://github.com/sidekiq-cron/sidekiq-cron/blob/master/lib/sidekiq/cron/web.rb
- Remove all the current usage of inline styles (instead of adding a custom css file). Ref: https://github.com/search?q=repo%3Asidekiq-cron%2Fsidekiq-cron+style%3D&type=code

**Comment by satyakampandya** [comment]
> > Remove all the current usage of inline styles (instead of adding custom css, I'd much prefer to simplify the view layer to use existing css classes or another solution that avoids inline styles). Ref: https://github.com/search?q=repo%3Asidekiq-cron%2Fsidekiq-cron+style%3D&type=code
> 
> Hi @markets,
> 
> I've started working on cleaning up the inline CSS as discussed. However, I noticed that the "Show All" button on the CronJob listing page isn't functioning as expected. When clicked, it doesn’t display the full message. Could you please confirm if this is a known issue?
> 
> To resolve this, we might need to add a few lines of JavaScript, or alternatively, we could consider removing the button from the UI if it's not essential.

@markets Could you please confirm if the "Show All" button on the CronJob listing page is supposed to be functional? From what I can see, it's currently not working, and fixing it would require some JavaScript.

If it's not essential, would you be open to removing the button instead?

**Comment by markets** [comment]
Sorry, I currently don't remember well what this button does, but maybe we can try with some HTML native apis, like the for example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details. I prefer to avoid injecting assets, as that will require even more changes for all the different supported versions. At the end, this is just an internal panel for admins, no need to look super cool, but functional.
