### ISSUE TITLE
Rails - trying to configer namespace via initializer fails with undefined method `configure'

### ISSUE THREAD

**Issue by thisIsLoading** [sidekiq-cron/sidekiq-cron#469]
Hi,

i was trying to configure the namespace as per the readme via an initializer in `/config/initializers/sidekiq-cron.rb`

```
Sidekiq::Cron.configure do |config|
  config.default_namespace = "foobar_#{Rails.env}"
end
```

but it throws a NoMethodError:

```
NoMethodError: undefined method `configure' for module Sidekiq::Cron (NoMethodError)

Sidekiq::Cron.configure do |config|
                     ^^^^^^^^^^
```

what do i do wrong?

**Comment by markets** [comment]
That feature is still unreleased, but hopefully we'll release a new version soon! In the meantime, you can point the gem to GitHub `master` branch: 

```ruby
gem 'sidekiq-cron', github: 'sidekiq-cron/sidekiq-cron'
```
