### ISSUE TITLE
"`create` method will return only true/false if job was saved or not". Is it so?

### ISSUE THREAD

**Issue by delphaber** [sidekiq-cron/sidekiq-cron#471]
Hello, the README says so:

https://github.com/sidekiq-cron/sidekiq-cron/blob/d409af416afa83362767880f57bb4bf432a80708/README.md?plain=1#L245

but the Sidekiq::Cron::Job.create method actually will return an integer instead of `true`.

That's because the last line of `save` method is this:

https://github.com/sidekiq-cron/sidekiq-cron/blob/d409af416afa83362767880f57bb4bf432a80708/lib/sidekiq/cron/job.rb#L492

which will return an integer. It's not a big deal, when using the return value of `create` in a truthy / falsey condition, but I think it's a little bug. What do you think?

**Comment by markets** [comment]
Hey @delphaber 👋 I agree, not a big deal, but should be fixed. Please, feel free to send a patch. Thanks!

**Comment by delphaber** [comment]
I will :)

**Comment by delphaber** [comment]
Oooops, sorry! Forgot about this :) I have a free hour now, I'm going to try to fix it!

**Comment by markets** [comment]
Closed by #476
