### ISSUE TITLE
The `date_as_argument` option cannot be changed from `true` to `false`

### ISSUE THREAD

**Issue by iwaseasahi** [sidekiq-cron/sidekiq-cron#472]
### Versions

| target | vertions |
| :--- | :--- |
| Ruby | 3.3.3 |
| Rails | 7.1.3.4 |
| sidekiq | 7.3.0 |
| sidekiq-cron | 1.12.0 |

### Summary

The `date_as_argument` option cannot be changed from `true` to `false`.

### Detail

I define the following.

`config/sidekiq_cron.yml`

```yml
send_sidekiq_metrics_job:
  cron: 0 * * * * * # Runs once per minute
  class: SendSidekiqMetricsJob
  date_as_argument: false
```

`config/initializers/sidekiq.rb`

```rb
require 'sidekiq/web'

Sidekiq.configure_server do |config|
  config.redis = {
    url: ENV.fetch('SIDEKIQ_REDIS_URL', ''),
  }

  config.on(:startup) do
    cron = YAML.load_file(File.expand_path('../../sidekiq_cron.yml', __FILE__))
    Sidekiq::Cron::Job.load_from_hash!(cron, source: 'schedule')
  end
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: ENV.fetch('SIDEKIQ_REDIS_URL', ''),
  }
end
```

And when I make the following changes, the changes do not take effect.

① Define `date_as_argument` with false.（When I start sidekiq, it's `false`）

```rb
irb(main):001> Sidekiq::Cron::Job.all
2024-07-12T08:21:23.392Z pid=88304 tid=22es INFO: Sidekiq 7.3.0 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://localhost:6379"}
=>
[#<Sidekiq::Cron::Job:0x0000000135d65e80
  ...
  @date_as_argument=false,
  @klass="SendSidekiqMetricsJob",
  ...
]
```

② `date_as_argument` be changed from false to true（When I start sidekiq, it's `true`）

```rb
irb(main):001> Sidekiq::Cron::Job.all
2024-07-12T08:22:43.534Z pid=88600 tid=22qk INFO: Sidekiq 7.3.0 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://localhost:6379"}
=>
[#<Sidekiq::Cron::Job:0x000000012bcc9260
  ...
  @date_as_argument=true,
  @klass="SendSidekiqMetricsJob",
  ...
]
```

③ `date_as_argument` be changed from true to false（When I start sidekiq, it's still `true`）

```rb
irb(main):001> Sidekiq::Cron::Job.all
2024-07-12T08:23:21.695Z pid=88887 tid=22yb INFO: Sidekiq 7.3.0 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://localhost:6379"}
=>
[#<Sidekiq::Cron::Job:0x0000000132c6e250
  ...
  @date_as_argument=true,
  @klass="SendSidekiqMetricsJob",
  ...
]
```

**Comment by satyakampandya** [comment]
@markets I found that once `date_as_argument` is set to `true`, and then we try to set it back to `false`, we're not updating anything in Redis, which is why it stays `true` afterwards. This issue might have been introduced by this [PR](https://github.com/sidekiq-cron/sidekiq-cron/pull/392/files#diff-45ac47a9faa0840538f2cae00fdd31667a33fb6b4f94a7428d9c80bceaf8a87eL407). I have a potential solution in mind for this issue. If you can confirm the issue, I’d be happy to raise a PR with the fix.
