### ISSUE TITLE
Cron jobs loaded but not running on Heroku-24

### ISSUE THREAD

**Issue by jchan172** [sidekiq-cron/sidekiq-cron#473]
On my machine, sidekiq-cron 1.8.0 works fine (with sidekiq 6.4.2), and production Heroku-20 and Heroku-22 machine has been fine as well. I upgraded to Heroku-24 a few days ago, and the sidekiq-cron isn't enqueueing jobs anymore.
- Cron jobs are all loaded (seen in UI and checking via console `Sidekiq::Cron::Job.all`
- Cron jobs all have status "Enabled"
- UI buttons "Enqueue Now" and "Disable" don't work for active jobs. Disabled jobs have buttons, and those don't work (can't enqueue, disable, nor delete).
- Jobs' "last enqueued" was 4 days ago when I upgraded to Heroku-24
- I've tried running `Sidekiq::Cron::Job.all.first.enque!`, and it enqueued and ran it.

Could it be an issue with poller? What can I do to fix this issue?

**Comment by markets** [comment]
Hey @jchan172 👋🏼 

Sorry I don't use Heroku nowadays, so I don't follow their stack changes anymore. 

It will really hard (mostly impossible) for us to help you with those specific versions of Sidekiq, Sidekiq-Cron, Heroku and the rest of gems and code of your app, without having a access to a reproducible scenario. I recommend you to update to more recent versions of Sidekiq and Sidekiq-Cron and see what happens.

Please, if you can provide an example app that reproduces the error locally or a failing test in our suite, don't hesitate to re-open the issue and I'll take a deeper look.

Kind regards,
Marc
