### ISSUE TITLE
Add Pagination to Cron Job Listing Page for Improved Usability

### ISSUE THREAD

**Issue by satyakampandya** [sidekiq-cron/sidekiq-cron#474]
Currently, the cron job listing page in the Sidekiq-Cron web UI displays all cron jobs in a single view. This can become cumbersome and inefficient when managing a large number of jobs, as users must scroll extensively to find or review specific entries. Adding pagination to this page would enhance the user experience by making navigation more manageable and the interface more responsive.

**Comment by markets** [comment]
Closing for now, please read the discussion in #477 for further information.
