### ISSUE TITLE
Deprecation Warning "Using the last argument as keyword parameters is deprecated"

### ISSUE THREAD

**Issue by jvanderen1** [sidekiq-cron/sidekiq-cron#478]
In our codebase, we have Ruby 3 deprecation warnings enabled via:

```ruby
Warning[:deprecated] = true
```

When we run a cron job via `load_from_hash`:

```ruby
schedule_file = "config/schedule.yml"

if File.exist?(schedule_file) && Sidekiq.server?
  schedule_hash = YAML.load_file(schedule_file)
  Sidekiq::Cron::Job.load_from_hash schedule_hash
end
```

We always end up seeing a warning message:

```
/usr/local/bundle/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:472: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

Is this a known issue with `sidekiq-cron` or has this been fixed in versions > 1.10.1?

**Comment by markets** [comment]
Hello @jvanderen1 and thanks for reporting this warning. This is not tracked yet in any issue or PR, so feel free to send a patch! We'd be very happy to review it 🤝 

Btw, you can already remove this file now, as it will be automatically picked by the [gem itself](https://github.com/sidekiq-cron/sidekiq-cron/blob/master/lib/sidekiq/cron/schedule_loader.rb): https://github.com/sidekiq-cron/sidekiq-cron?tab=readme-ov-file#loading-jobs-from-schedule-file.

**Comment by jvanderen1** [comment]
@markets Thank you for the suggestion! In the example above, I did omit some smaller details. For example, before we start any cronjobs, we actually delete any active one's first.

i.e.
```ruby
### First delete all jobs
Sidekiq::Cron::Job.all.each(&:destroy)

### Then load config/schedule.yml and restart
schedule_file = "config/schedule.yml"
if File.exist?(schedule_file) && Sidekiq.server?

  schedule_hash = YAML.load_file(schedule_file)
  Sidekiq::Cron::Job.load_from_hash schedule_hash
end
```

Is this necessary to do or will the gem automatically delete stale jobs when `require`d?

**Comment by markets** [comment]
In the schedule loader we are using the bang suffixed methods:

https://github.com/sidekiq-cron/sidekiq-cron/blob/81268643b8fe4bb0a2197cb650b16a115a220c6f/lib/sidekiq/cron/schedule_loader.rb#L12

https://github.com/sidekiq-cron/sidekiq-cron/blob/81268643b8fe4bb0a2197cb650b16a115a220c6f/lib/sidekiq/cron/job.rb#L248-L249

Those methods☝️ clean up old jobs. So yes, you can delete your custom load file. I'd also recommend to upgrade to the last version: https://github.com/sidekiq-cron/sidekiq-cron/blob/master/CHANGELOG.md#1120.

**Comment by jvanderen1** [comment]
I went ahead and created https://github.com/sidekiq-cron/sidekiq-cron/pull/479. Thank you!
