### ISSUE TITLE
Missing confirmation before enqueuing disabled jobs

### ISSUE THREAD

**Issue by satyakampandya** [sidekiq-cron/sidekiq-cron#481]
When attempting to enqueue a cron job, the behaviour differs based on whether the job is enabled or disabled:
- When the job is enabled: The user is prompted with a confirmation dialog (data-confirm) before the job is enqueued.
- When the job is disabled: The job is enqueued directly without asking for confirmation.

This inconsistency can lead to accidental enqueuing of disabled jobs, especially since users may expect a confirmation dialog before taking action, regardless of the job's current status.

### Expected behaviour:
Whether a job is enabled or disabled, the system should consistently ask for confirmation before enqueuing the job, similar to how confirmation is required before deleting or enqueuing enabled jobs.

### Actual Behavior:
- Enabled jobs: The system correctly displays a confirmation dialog before enqueuing.
- Disabled jobs: The system does not display a confirmation dialog, and the job is enqueued immediately when the "Enqueue Now" button is clicked.

### Steps to Reproduce:
- Navigate to the cron job management page.
- Find a disabled job.
- Click the "Enqueue Now" button for the disabled job.
- Observe that the job is enqueued immediately without any confirmation prompt.

I'm happy to raise a PR to address this issue and ensure the system behaves consistently when enqueuing jobs, regardless of their status.

**Comment by satyakampandya** [comment]
@markets Would you be open to a PR that addresses this issue and ensures consistent confirmation behavior for all jobs? Please let me know if this is something you’d like to have fixed.

**Comment by markets** [comment]
Ok! let's make it consistent 👍🏼 feel free to send a PR
