### ISSUE TITLE
Unable to perform job actions when accessing /monitoring/sidekiq/cron/namespaces/*

### ISSUE THREAD

**Issue by satyakampandya** [sidekiq-cron/sidekiq-cron#483]
When visiting `/monitoring/sidekiq/cron/namespaces/*` within Sidekiq-cron, it becomes impossible to perform any actions on individual jobs. This happens because the job being requested with a `*` wildcard in the namespace and name does not exist in the Sidekiq-cron job list, which is scoped by the job's actual namespace.

#### Expected Behavior:
- When accessing `/monitoring/sidekiq/cron/namespaces/*`, actions like `"Enqueue Now"`, `"Delete"`, `"Enable"` and `"Disable"` should function correctly for the jobs under that namespace.
- The job's namespace should be properly identified in order to allow for per-job actions.

#### Actual Behavior:
- When visiting `/monitoring/sidekiq/cron/namespaces/*`, no actions can be performed on individual jobs.
- The system fails to find the correct job, as it tries to locate jobs under the `*` namespace and the job name, which doesn’t exist.
- The system should be requesting actions using the job's actual namespace instead of *.

#### Steps to Reproduce:
- Visit `/monitoring/sidekiq/cron/namespaces/*` in a Sidekiq-cron setup with jobs that use namespaces.
- Attempt to perform any action on a job (e.g., `"Enqueue Now"`).
- Notice that the action fails because the system is trying to find the job under the `*` namespace instead of the actual namespace.

#### Suggested Solution:
- The job actions should use the job's actual namespace for making requests, instead of relying on `*` in the namespace.
- The request URL should be adjusted to include the correct namespace when performing actions.

**Comment by satyakampandya** [comment]
Additionally, it should be restricted to create jobs with a namespace of `*`, as it causes routing conflicts and leads to operational issues. Here's an example that should ideally raise an error:

```ruby
Sidekiq::Cron::Job.create(
  name: 'Hard worker - every 5min',
  namespace: '*',
  cron: '*/5 * * * *',
  class: 'HardWorker'
)
```

This restriction could prevent the routing problem and ensure namespaces are properly used.

**Comment by markets** [comment]
Agree @satyakampandya we should fix those things!

> it should be restricted to create jobs with a namespace of *

Agree also on that ☝🏼.
