### ISSUE TITLE
Web extension requires entire sidekiq-cron to be required

### ISSUE THREAD

**Issue by freemanoid** [sidekiq-cron/sidekiq-cron#486]
Currently, I'm using 1.12.0

I've tried the latest version `2.0.0.rc1`, `65020e5ff3ebd849516a925206aca523682dd64c`

In `routes.rb` I have a single `sidekiq-cron` require

```ruby
require "sidekiq/cron/web"
```

In Gemfile:

```ruby
gem "sidekiq-cron", :require => false
```

When I try to start a webserver to serve sidekiq web UI, and go to `/sidekiq/cron`, it throws an exception

```ruby
NameError (uninitialized constant Sidekiq::Cron::Namespace):
```

Then I add a missing require to `routes.rb` 

```ruby
require "sidekiq/cron/namespace"
```

And it fails with the following exception

```ruby
NoMethodError (undefined method `configuration' for Sidekiq::Cron:Module

          name == Sidekiq::Cron.configuration.default_namespace
                               ^^^^^^^^^^^^^^):
```

Now, the only way to require `Sidekiq::Cron.configuration` is to require the entire `sidekiq-cron`. That seems unnecessary to me. IMO, it makes sense to decouple `Sidekiq::Cron::Configuration` from `sidekiq/cron.rb`, so it can be required separately. 
So `sidekiq/cron/web` requirements section would look like:

```ruby
require "sidekiq/cron/namespace"
require "sidekiq/cron/configuration"
...
```

And `Sidekiq::Cron.configure` can be forwarded to `Sidekiq::Cron::Configuration` 

Also, it's probably worth mentioning in the README that configuration must be loaded for the web UI due to default namespace, not just for sidekiq instance.

I'm happy to make a PR if that approach makes sense.

**Comment by markets** [comment]
@freemanoid I think that make sense 👍

**Comment by freemanoid** [comment]
> @freemanoid I think that make sense 👍

Here you go 🤝  https://github.com/sidekiq-cron/sidekiq-cron/pull/487
