### ISSUE TITLE
Problem with queue in Rails 7.2

### ISSUE THREAD

**Issue by pyromaniac** [sidekiq-cron/sidekiq-cron#512]
Hello, 

First of all, thanks for the great gem and all the effort!

In Rails 7.2 and sidekiq-cron 2.0, SomeJob.queue_name returns a proc if not set explicitly:

```
class SomeJob < ActiveJob::Base
end

SomeJob.queue_name
=> #<Proc:0x0000000331a82f08 activejob-7.2.2/lib/active_job/queue_name.rb:55 (lambda)>
Sidekiq::Cron::Job.new(name: 'something', class: 'SomeJob', cron: 'every 10 minutes')
=> #<Sidekiq::Cron::Job:0x00000003335ffdd0
 @active_job=false,
 @active_job_queue_name_delimiter=nil,
 @active_job_queue_name_prefix=nil,
 @args=[],
 @cron="every 10 minutes",
 @date_as_argument=false,
 @fetch_missing_args=true,
 @klass="SomeJob",
 @last_enqueue_time=nil,
 @message={"queue"=>#<Proc:0x0000000331a82f08 activejob-7.2.2/lib/active_job/queue_name.rb:55 (lambda)>, "class"=>"SomeJob", "args"=>[]},
 @name="something",
 @namespace="default",
 @queue=#<Proc:0x0000000331a82f08 activejob-7.2.2/lib/active_job/queue_name.rb:55 (lambda)>,
 @queue_name_with_prefix="some_prefix_#<Proc:0x0000000331a82f08 activejob-7.2.2/lib/active_job/queue_name.rb:55 (lambda)>",
 @retry=nil,
 @source="dynamic",
 @status="enabled",
 @symbolize_args=false>
```

This leads to inability to execute the scheduled job.

The workaround is either to pass `queue:` explicitly to `Sidekiq::Cron::Job.new` or define `queued_as` explicitly in `SomeJob`.
But I believe it might break some production code and get unnoticed.

**Comment by markets** [comment]
Hey @pyromaniac Do you know when this started to happen? Do you detected this with the v2 release?

**Comment by pyromaniac** [comment]
Hey @markets, sorry but no. Noticed it on 2.0 upgrade.

**Comment by markets** [comment]
Would you like to explore a solution?

**Comment by leoarnold** [comment]
In my setup, the problem seems to stem from this line

https://github.com/sidekiq-cron/sidekiq-cron/blob/b93aec83d3a8c31834b071d4da61f4f48cf97aba/lib/sidekiq/cron/job.rb#L63

in which `message_data['queue']` is a `Proc`.

This may or may not be related to an effort in Rails where they wanted to allow the QueueAdaptor to deceide on the default queue name, rather than ActiveJob asserting it, hence a `Proc` rather than a `String` (Sorry, couldn't find a link to that effort yet).

**Comment by leoarnold** [comment]
The matching line in v1.12.0

https://github.com/sidekiq-cron/sidekiq-cron/blob/3bce29b908239f5fb40ca0794582aaaf21e07079/lib/sidekiq/cron/job.rb#L308

gets `message_data['queue']` as `"default"`. I used Sidekiq 7.3.2 for both explorations.

**Comment by leoarnold** [comment]
I guess this is the root cause:

https://github.com/sidekiq-cron/sidekiq-cron/blob/v2.0.0/lib/sidekiq/cron/job.rb#L806-L807

It's new in v2.0.0, but since `.queue_name` is a `Proc`, this does not work as intended.

**Comment by markets** [comment]
Thanks for the investigation @leoarnold 👌🏼 I think we can fix it by something like:

```ruby
klass.queue_name.respond_to?(:call) ? klass.queue_name.call : klass.queue_name
```

Please, feel free to send a patch.

**Comment by pyromaniac** [comment]
@markets not really:

```
SomeJob.queue_name.call
NoMethodError: undefined method `default_queue_name' for class Class
from gems/activejob-7.2.2/lib/active_job/queue_name.rb:55:in `block (2 levels) in <module:QueueName>'
```

I'm not sure yes what did they do there.

**Comment by leoarnold** [comment]
@pyromaniac PR #517 is up. Could you give it a test run on your systems?

```ruby
gem "sidekiq-cron", github: "leoarnold/sidekiq-cron", branch: "leoarnold/queue_name"
```

**Comment by markets** [comment]
@pyromaniac @leoarnold New version pushed to RubyGems: https://github.com/sidekiq-cron/sidekiq-cron/releases/tag/v2.0.1
