### ISSUE TITLE
[Bug] Redis data corruption due to incorrect `.flatten` call in `Sidekiq::Cron::Job#save` method

### ISSUE THREAD

**Issue by iwaseasahi** [sidekiq-cron/sidekiq-cron#513]
## Verion

sidekiq-cron: 2.0.0

## Description

There's a bug in the `Sidekiq::Cron::Job#save` method where calling `.flatten` on the transformed hash causes data corruption in Redis. This results in jobs being saved with incorrect data structure and nil attributes when retrieved.

## Current Behavior

The current implementation in `Sidekiq::Cron::Job#save`:

https://github.com/sidekiq-cron/sidekiq-cron/blob/464c5dc24f81946f11d319181c491b77bd8858f4/lib/sidekiq/cron/job.rb#L483-L484

This causes the hash to be flattened into a single array, resulting in Redis storing data like:

```rb
{
  "[:name, \"job_name\", :namespace, \"default\", ...]" => ""
}
```

## Expected Behavior

The hash should be stored with proper key-value pairs:

```rb
{
  "name" => "job_name",
  "namespace" => "default",
  ...
}
```

## Proposed Fix

Remove the `.flatten` call from `Sidekiq::Cron::Job#save`.
This issue was introduced by PR #479.

**Comment by markets** [comment]
Hmm 🤔 that's weird, as per https://github.com/sidekiq-cron/sidekiq-cron/pull/479#issuecomment-2338906477 this is the way to pass arguments to hset. 

@jvanderen1 any thoughs?

**Comment by iwaseasahi** [comment]
@jvanderen1 
Thanks your comment.

The issue isn't with how `hset` stores the data, but rather with the data structure transformation that occurs before storage. The problem arises because `Sidekiq::Cron::Job.all` expects to process hash data from Redis, not flattened arrays.

Let me explain with the relevant code:

In `Sidekiq::Cron::Job.all`, the code processes Redis data like this:

https://github.com/sidekiq-cron/sidekiq-cron/blob/df5b8cf4578a0e079ed33d3fbbf7d9b3ed5c79c1/lib/sidekiq/cron/job.rb#L292-L307

While your Redis example shows the data can be retrieved, the issue is that `Sidekiq::Cron::Job` internals are designed to work with hash structures, not arrays. The `.flatten` call transforms the data structure in a way that breaks this assumption.

**Comment by jvanderen1** [comment]
@iwaseasahi I appreciate the response!

With the example you provided, I am still unsure any data corruption is occurring. The only areas I can see possibly being problematic are lines 297 - 301. But with some testing, I still don't see an issue:

```ruby
> require 'redis';
> redis = Redis.new;
> redis.hgetall('key1') # From flatten example earlier
=> {"foo"=>"bar", "baz"=>"biz"}
> my_hash_2 = {'aaa': '1', 'zzz': '2'};
> redis.hset 'key2', my_hash_2.transform_values! { |v| v || '' }; # Key/values stored without flatten method
> redis.pipelined do |pipeline|
*   ['key1', 'key2'].each { |key| pipeline.hgetall(key) }
* end
=> [{"foo"=>"bar", "baz"=>"biz"}, {"aaa"=>"1", "zzz"=>"2"}] # Still returns hashes
```

Also, taking a look at the `redis-client` macOS library, it appears these values are stored the same under the hood:

```
# `key1` was stored with `flatten`
> HGETALL key1
1) "foo"
2) "bar"
3) "baz"
4) "biz"
# `key2` was stored without `flatten`
> HGETALL key2
1) "aaa"
2) "1"
3) "zzz"
4) "2"
```

I would like to better understand what bug(s) you see are occurring due to `flatten`:
- Which line(s) specifically are not receiving the correct data structure? In the example provided, the data structures from lines 297 - 301 look nominal.
- Do you observe any differences in the library's execution? Are things failing or throwing an error?
- Can you provide a minimum reproducible script just using Redis?

**Comment by iwaseasahi** [comment]
@jvanderen1 
I apologize for my misunderstanding.

The issue I thought I found was actually due to the difference in behavior between MockRedis used in our test environment and the actual Redis implementation.

With actual Redis:

```ruby
hash = {:name=>"job", :namespace=>"default", :klass=>"Job"}
hash.transform_values! { |v| v || '' }
redis.hset("key", hash.flatten)
redis.hgetall("key")
=> {"name"=>"job", "namespace"=>"default", "klass"=>"Job"}
```

https://github.com/sds/mock_redis

While with MockRedis:

```rb
hash = {:name=>"job", :namespace=>"default", :klass=>"Job"}
hash.transform_values! { |v| v || '' }
mock_redis.hset("key", hash.flatten)
mock_redis.hgetall("key")
=> {"[:name, \"job\", :namespace, \"default\", :klass, \"Job\"]"=>""}
```

The cause is the following code.
https://github.com/sds/mock_redis/blob/30eb1bc683fa2316372cad555a323c5a573e8f5e/lib/mock_redis/hash_methods.rb#L138-L151

I was wrong in my previous assessment. Thank you for bringing this to my attention.

**Comment by iwaseasahi** [comment]
`Sidekiq::Cron::Job#save` had no problems, so close this issue.
